// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: Service1.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HiRequest) Reset() {
	*x = HiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Service1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiRequest) ProtoMessage() {}

func (x *HiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Service1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiRequest.ProtoReflect.Descriptor instead.
func (*HiRequest) Descriptor() ([]byte, []int) {
	return file_Service1_proto_rawDescGZIP(), []int{0}
}

func (x *HiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HiReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HiReply) Reset() {
	*x = HiReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Service1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiReply) ProtoMessage() {}

func (x *HiReply) ProtoReflect() protoreflect.Message {
	mi := &file_Service1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiReply.ProtoReflect.Descriptor instead.
func (*HiReply) Descriptor() ([]byte, []int) {
	return file_Service1_proto_rawDescGZIP(), []int{1}
}

func (x *HiReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Service1_proto protoreflect.FileDescriptor

var file_Service1_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1f, 0x0a, 0x09, 0x48, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x23, 0x0a, 0x07, 0x48, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2c, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x31, 0x12, 0x1c, 0x0a, 0x02, 0x48, 0x69, 0x12, 0x0a, 0x2e, 0x48,
	0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x48, 0x69, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Service1_proto_rawDescOnce sync.Once
	file_Service1_proto_rawDescData = file_Service1_proto_rawDesc
)

func file_Service1_proto_rawDescGZIP() []byte {
	file_Service1_proto_rawDescOnce.Do(func() {
		file_Service1_proto_rawDescData = protoimpl.X.CompressGZIP(file_Service1_proto_rawDescData)
	})
	return file_Service1_proto_rawDescData
}

var file_Service1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Service1_proto_goTypes = []interface{}{
	(*HiRequest)(nil), // 0: HiRequest
	(*HiReply)(nil),   // 1: HiReply
}
var file_Service1_proto_depIdxs = []int32{
	0, // 0: ProtoServer1.Hi:input_type -> HiRequest
	1, // 1: ProtoServer1.Hi:output_type -> HiReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Service1_proto_init() }
func file_Service1_proto_init() {
	if File_Service1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Service1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Service1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Service1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Service1_proto_goTypes,
		DependencyIndexes: file_Service1_proto_depIdxs,
		MessageInfos:      file_Service1_proto_msgTypes,
	}.Build()
	File_Service1_proto = out.File
	file_Service1_proto_rawDesc = nil
	file_Service1_proto_goTypes = nil
	file_Service1_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProtoServer1Client is the client API for ProtoServer1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProtoServer1Client interface {
	Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error)
}

type protoServer1Client struct {
	cc grpc.ClientConnInterface
}

func NewProtoServer1Client(cc grpc.ClientConnInterface) ProtoServer1Client {
	return &protoServer1Client{cc}
}

func (c *protoServer1Client) Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error) {
	out := new(HiReply)
	err := c.cc.Invoke(ctx, "/ProtoServer1/Hi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoServer1Server is the server API for ProtoServer1 service.
type ProtoServer1Server interface {
	Hi(context.Context, *HiRequest) (*HiReply, error)
}

// UnimplementedProtoServer1Server can be embedded to have forward compatible implementations.
type UnimplementedProtoServer1Server struct {
}

func (*UnimplementedProtoServer1Server) Hi(context.Context, *HiRequest) (*HiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hi not implemented")
}

func RegisterProtoServer1Server(s *grpc.Server, srv ProtoServer1Server) {
	s.RegisterService(&_ProtoServer1_serviceDesc, srv)
}

func _ProtoServer1_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoServer1Server).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProtoServer1/Hi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoServer1Server).Hi(ctx, req.(*HiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProtoServer1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProtoServer1",
	HandlerType: (*ProtoServer1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _ProtoServer1_Hi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Service1.proto",
}
